$axure.loadCurrentPage({
  "url":"page_2.html",
  "generationDate":new Date(1414658162031.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tuodong",
"GDGN1",
"n",
"m",
"w",
"k"],
  "page":{
    "packageId":"1a89a4f890434833bae083d27a7c2533",
    "type":"Axure:Page",
    "name":"Page 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});