$axure.loadCurrentPage({
  "url":"page_1.html",
  "generationDate":new Date(1416730699987.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"tuodong",
"GDGN1",
"n",
"m",
"w",
"k",
"lan"],
  "page":{
    "packageId":"5f579a55e6f6498c8e82b42d5d8434e1",
    "type":"Axure:Page",
    "name":"Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});